-- mysql

-- CREATE DATABASE IF NOT EXISTS source;
-- GRANT ALL PRIVILEGES ON source.* TO 'demo'@'%';

CREATE DATABASE IF NOT EXISTS slot1;
GRANT ALL PRIVILEGES ON slot1.* TO 'demo'@'%';

CREATE DATABASE IF NOT EXISTS slot2;
GRANT ALL PRIVILEGES ON slot2.* TO 'demo'@'%';

CREATE DATABASE IF NOT EXISTS slot3;
GRANT ALL PRIVILEGES ON slot3.* TO 'demo'@'%';

CREATE DATABASE IF NOT EXISTS slot4;
GRANT ALL PRIVILEGES ON slot4.* TO 'demo'@'%';

CREATE DATABASE IF NOT EXISTS slot5;
GRANT ALL PRIVILEGES ON slot5.* TO 'demo'@'%';