-- postgresql

CREATE SCHEMA IF NOT EXISTS slot1 AUTHORIZATION demo;
CREATE SCHEMA IF NOT EXISTS slot2 AUTHORIZATION demo;
CREATE SCHEMA IF NOT EXISTS slot3 AUTHORIZATION demo;
CREATE SCHEMA IF NOT EXISTS slot4 AUTHORIZATION demo;
CREATE SCHEMA IF NOT EXISTS slot5 AUTHORIZATION demo;
-- ALTER ROLE demo SET search_path = source, public;